# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
