# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 05:32
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160926_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='foto'),
        ),
    ]
